# **Numpy Practice Questions**

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [1]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
vertically_stacked = np.vstack((A, B))
horizontally_stacked = np.hstack((A,B))
print(vertically_stacked)
print(horizontally_stacked)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [2]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([1, 2, 4, 6, 8, 9])
common_elements = np.array(list(set(A) & set(B)))
print(common_elements)

[1 2 4 6]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [3]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
extracted_indices = np.where((A >= 5) & (A <= 10))
print(A[extracted_indices])

[ 5  6  7  8  9 10]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

  url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

  iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filtered_iris_2d = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_iris_2d)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# **Practice Questions for Pandas**

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [5]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df['Min.Price'], df['Max.Price'], "\n---------------------")
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df['Min.Price'], df['Max.Price'])

0     12.9
1     29.2
2     25.9
3      NaN
4      NaN
      ... 
88    16.6
89    17.6
90    22.9
91    21.8
92    24.8
Name: Min.Price, Length: 93, dtype: float64 0     18.8
1     38.7
2     32.3
3     44.6
4      NaN
      ... 
88    22.7
89    22.4
90    23.7
91    23.5
92    28.5
Name: Max.Price, Length: 93, dtype: float64 
---------------------
0     12.900000
1     29.200000
2     25.900000
3     17.118605
4     17.118605
        ...    
88    16.600000
89    17.600000
90    22.900000
91    21.800000
92    24.800000
Name: Min.Price, Length: 93, dtype: float64 0     18.800000
1     38.700000
2     32.300000
3     44.600000
4     21.459091
        ...    
88    22.700000
89    22.400000
90    23.700000
91    23.500000
92    28.500000
Name: Max.Price, Length: 93, dtype: float64


3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [7]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df,"\n-----------------")
rows = df[df.sum(axis=1) > 100]
print(rows)

     0   1   2   3
0   39  17  15  12
1   37  17  36  34
2   23  15  22  16
3   15  19  15  11
4   21  27  24  13
5   27  19  32  34
6   38  20  13  39
7   37  27  12  16
8   21  24  10  28
9   23  37  28  16
10  36  36  39  26
11  27  16  15  34
12  34  27  19  17
13  10  34  18  14
14  11  36  22  22 
-----------------
     0   1   2   3
1   37  17  36  34
5   27  19  32  34
6   38  20  13  39
9   23  37  28  16
10  36  36  39  26
